const METRIC_TYPES = {
  DISTANCE: 'DISTANCE',
  TEMPERATURE: 'TEMPERATURE',
};

const DISTANCE_UNITS = {
  METER: 'METER',
  CENTIMETER: 'CENTIMETER',
  INCH: 'INCH',
  FEET: 'FEET',
  YARD: 'YARD',
};

const TEMPERATURE_UNITS = {
  CELSIUS: 'CELSIUS',
  FAHRENHEIT: 'FAHRENHEIT',
  KELVIN: 'KELVIN',
};

module.exports = {
  METRIC_TYPES,
  DISTANCE_UNITS,
  TEMPERATURE_UNITS,
};

