const METRIC_TYPES = {
  DISTANCE: 'DISTANCE',
  TEMPERATURE: 'TEMPERATURE',
};

const DISTANCE_UNITS = {
  METER: 'METER',
  CENTIMETER: 'CENTIMETER',
  INCH: 'INCH',
  FEET: 'FEET',
  YARD: 'YARD',
};

const TEMPERATURE_UNITS = {
  CELSIUS: 'CELSIUS',
  FAHRENHEIT: 'FAHRENHEIT',
  KELVIN: 'KELVIN',
};

const UNIT_MAPPING = {
  [DISTANCE_UNITS.METER]: METRIC_TYPES.DISTANCE,
  [DISTANCE_UNITS.CENTIMETER]: METRIC_TYPES.DISTANCE,
  [DISTANCE_UNITS.INCH]: METRIC_TYPES.DISTANCE,
  [DISTANCE_UNITS.FEET]: METRIC_TYPES.DISTANCE,
  [DISTANCE_UNITS.YARD]: METRIC_TYPES.DISTANCE,
  [TEMPERATURE_UNITS.CELSIUS]: METRIC_TYPES.TEMPERATURE,
  [TEMPERATURE_UNITS.FAHRENHEIT]: METRIC_TYPES.TEMPERATURE,
  [TEMPERATURE_UNITS.KELVIN]: METRIC_TYPES.TEMPERATURE,
}

module.exports = {
  METRIC_TYPES,
  DISTANCE_UNITS,
  TEMPERATURE_UNITS,
  UNIT_MAPPING,
};

